// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EDevTool","status":true,"description":"v0.0.1 Bare Bones Plugin Template","parameters":{}},
{"name":"EDisplayImage","status":true,"description":"v0.0.1 Bare Bones Plugin Template","parameters":{}}
];
